In [ ]:
# Write a program to find the sum of prime factors of given 
# number
import functools

def sum(x,y):
  return x + y

def prime_num(num):
  c = 0 
  for i in range(1,num):
    if num % i ==0:
      c+=1
  if c==1:
    return 1

num = 15
list1 = []# list
for i in range(1,num+1):
  if num % i ==0:
    list1.append(i)
print(list1)

prime_sum = list(filter(prime_num,list1))
print(prime_sum)

print(functools.reduce(sum,prime_sum))

[1, 3, 5, 15]
[3, 5]
8

# DATA STRUCTURES
A data structure is a group of elements that are put together under one name. 

A data structure defines a particluar way of storing and organizing data, so that it is used efficiently.

#SEQUENCE 
It is the most basic data structure in Python.In a sequence :

*   Every element in a sequence has a specific index.
*   The index value starts from zero and incremented for the next element in the sequence.
* Sequence is a generic term ordered set.
* Lists and tuples are the type of sequence.
* Python has some in-built functions which are used to manipulate.

# LISTS
Lists are similar to arrays. It is sequence in which elements are written as a list of comma-separated values between square brackets.

The important feature of the LISTS is that the 

* elements stored can be of different data types.
* Any number of elements can be stored.


```
List_variable = [val1, val2, ...]
```

In [ ]:
# Syntax for defining a list containing integers
list_numbers = [1,2,3,4]
print('list_numbers: ',list_numbers)


# Syntax for defining a list containing float numbers
list_float_numbers = [1.5, 2.7, 3.8, 4.9]
print('\nlist_float_numbers: ',list_float_numbers)


# Syntax for defining a list containing strings
list_strings = ['Hello', 'Good', 'Morning', 'Class']
print('\nlist_strings: ', list_strings)


# Syntax for defining a list containing strings
list_strings2 = ["Hello", "Good", "Morning", "Class"]
print('\nlist_strings2: ',list_strings2)


# Syntax for defining a list containing elements of different data types
list_elements = [1, 2.9, 'A', "Good Morning"]
print('\nlist_elements: ',list_elements)

l = 5
print(l)

list_numbers:  [1, 2, 3, 4]

list_float_numbers:  [1.5, 2.7, 3.8, 4.9]

list_strings:  ['Hello', 'Good', 'Morning', 'Class']

list_strings2:  ['Hello', 'Good', 'Morning', 'Class']

list_elements:  [1, 2.9, 'A', 'Good Morning']
5

# Access Values in LISTS

LISTS can also be sliced and concatenated like strings.

LISTS can also be accessed, square brackets are used to slice along with the index or indices to get value stored at that index.

```
# syntax
l = List[start: stop: step]
```

```
l = list[::2] -> get every other element, starting with index 0
l = list[1::2] -> get every  other element, starting with index 1
```

In [ ]:
num_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print('num_list is :', num_list)
print('First element in the list is :', num_list[0])
print('num_list[2:5] :', num_list[2:5])
print('num_list[::2] :', num_list[::2])
print('num_list[1::3]', num_list[1::3])

num_list is : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
First element in the list is : 1
num_list[2:5] : [3, 4, 5]
num_list[::2] : [1, 3, 5, 7, 9]
num_list[1::3] [2, 5, 8]

# Updating Values in a LISTS

One or more elements of a LIST can be easily updated by giving the slice on the left-hand side of the assignment operator.



*   New elements can be added to LIST using ***append()*** function 
*   Existing Elements can also be removed from the LIST using ***del*** statement.

In [ ]:
num_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print('num_list is :', num_list)

num_list[7] = 1000 # insert 1000 in index 7

print('List after updation is :', num_list)
num_list.append(-20) 
print(num_list)
# insert the element -20 at the end of the list

#print('num_list[2:5] :', num_list[2:5])
#print('List after adding a new element is :', num_list)

del num_list[4]
print('List after deleting element at num_list[4] -> 5 is :', num_list)

del num_list[2:5]
print('List after deleting element at num_list[2:5] -> 3,4,6 is :', num_list)

num_list is : [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
List after updation is : [1, 2, 3, 4, 5, 6, 7, 1000, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 1000, 9, 10, -20]
List after deleting element at num_list[4] -> 5 is : [1, 2, 3, 4, 6, 7, 1000, 9, 10, -20]
List after deleting element at num_list[2:5] -> 3,4,6 is : [1, 2, 7, 1000, 9, 10, -20]

In [ ]:
# Deleting all the elements in the list num_list
num_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
del num_list[:] # I have an empty pocket
print('List after deleting element at num_list[4] -> 5 is :', num_list)
#Deleteing the list num_list1
num_list1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(num_list1)
del num_list1 # i dont have a pocket
print('List', num_list1)

List after deleting element at num_list[4] -> 5 is : []
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

NameError: ignored

In [ ]:
# inserting a list in another list
list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = [20,30,40,50]
print('The orginal list : ',list1)
list1[4] = list2 # This is equal to list1[4] = [20,30,40,50]
print('The modified list :', list1)
print(list1[4])
print(list1[4][1])

The orginal list :  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
The modified list : [1, 2, 3, 4, [20, 30, 40, 50], 6, 7, 8, 9, 10]
[20, 30, 40, 50]
30

# Nested LISTS
Nested LIST means a list within another list. A list has elements of different data types which can include even a list.

In [ ]:
#nested list
list1 = [1, 'a', "abc", [2,3,4,5],8.9]

i=0
while i< len(list1):
  print('list1[',i,']->', list1[i])
  i+=1


i=3
j=0

print('\n')
while j < len(list1[3]):
  print('list1[',i,'][',j,']->', list1[i][j])
  j+=1

list1[ 0 ]-> 1
list1[ 1 ]-> a
list1[ 2 ]-> abc
list1[ 3 ]-> [2, 3, 4, 5]
list1[ 4 ]-> 8.9


list1[ 3 ][ 0 ]-> 2
list1[ 3 ][ 1 ]-> 3
list1[ 3 ][ 2 ]-> 4
list1[ 3 ][ 3 ]-> 5

#Cloning LISTS

If you want to modify a list and also keep a copy of the original list, then you should create a separate copy of the list.

This process is called ***cloning***.
This slice operation is used to clone a list.

In [ ]:
list1 = [1,2,3,4,5,6,7,8,9,10]
list2 = list1 # copies a list using reference
print('List1 = ', list1)
print('List2 = ', list2)
list2.append(1000)
print('List1 = ', list1)
print('List2 = ', list2)
del list1[3]
print('List1 = ', list1)
print('List2 = ', list2)
list3 = list2
del list3[:]
print('List1 = ', list1)
print('List2 = ', list2)
print('List3 = ',list3)
list3 = list1[3:8]
print('List3[3:8] = ', list3)

List1 =  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
List2 =  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
List1 =  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1000]
List2 =  [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1000]
List1 =  [1, 2, 3, 5, 6, 7, 8, 9, 10, 1000]
List2 =  [1, 2, 3, 5, 6, 7, 8, 9, 10, 1000]
List1 =  []
List2 =  []
List3 =  []
List3[3:8] =  []

In [ ]:
''' 
Basic List Operations
Lists is similar way as strings when operators like concatenation (+) and repetition (*)
'''
list4 = ['Hello world','Good Morning']
#print(list1*2)
print(list4*2)
list1 = [1,2,4,5,6]
print(list1 + list4 + list1)

['Hello world', 'Good Morning', 'Hello world', 'Good Morning']
[1, 2, 4, 5, 6, 'Hello world', 'Good Morning', 1, 2, 4, 5, 6]

# Basic Operations of the List

* len()           
* concatenation (+)
* repetition (*)
* in 
* not in
* max
* min
* sum
* all
* any
* list
* sorted

In [ ]:

#Operations on LIST
# len() -> returns the length of the list
print(len(list1))
print(len(list4))

5
2

In [ ]:
# in -> checks if the value is present in the list
list_vowels = ['a','e','i','o','u']
#print('a' in list_vowels)
#print('A' in list_vowels)
# not in -> checks if the value is not present in the list
print('e' not in list_vowels)
print('E' not in list_vowels)

False
True

In [ ]:
#max() -> returns maximum value in the list
print('Max value in the List ',max(list1))
print('Max value in the vowels : ',max(list_vowels))

#min() -> returns minimum value in the list
print('Min value in the List ',min(list1))
print('Min value in the vowels : ',min(list_vowels))

Max value in the List  6
Max value in the vowels :  u
Min value in the List  1
Min value in the vowels :  a

In [ ]:
# sum() -> adds the values in the list that has numbers
list1 = [10, 20, 30, 40, 50, 60, 70, 80, 10]
print('Sum of the numbers in the list : ', sum(list1))

Sum of the numbers in the list :  370

In [ ]:
# all() - > Returns True if all the elements of the list are true or if the list is empty
list1 = [1,2,3,5,6,-7]
print('Is all the elements of the list are non-zero',all(list1))
list10 =[]
print('Is the list is empty',all(list10))

Is all the elements of the list are non-zero True
Is the list is empty True

In [ ]:
# any() -> Returns True if any of the elements of the list are non-zero
list11 = [0,0,0,0,0,5]
print('Is any of  the elements of the list are non-zero',any(list11))
list12 =[0]
print('Is the list is empty',any(list12))

Is any of  the elements of the list are non-zero True
Is the list is empty False

In [ ]:
# list()  converts an iterable (tuple, string, set, dictionary) to a list
list13 = "Hello"
print(list13,'Type : ',type(list13))
list14 = list(list13)
print(list14,'Type : ',type(list14))

Hello Type :  <class 'str'>
['H', 'e', 'l', 'l', 'o'] Type :  <class 'list'>

In [ ]:
# sorted() Returns a new sorted list. The original list is not sorted

list14 = [3,4,1,2,7,8]
print(sorted(list14))

list15 = 'aHello'
print(sorted(list15))

[1, 2, 3, 4, 7, 8]
['H', 'a', 'e', 'l', 'l', 'o']

# LIST METHODS

* append()
* count()
* index()
* insert()
* pop()
* remove()
* reverse()
* sort()
* extend()

In [ ]:
# append() -> adds the element in the end of the list
print('The original list is : ',list1)
list1.append(50)
print('The list after adding the element in the end',list1)

In [ ]:
list16 = ['Hello', 'Students']
list16.append('CSE')
print('The list after adding the element in the end', list16)

In [ ]:
# count() -> Counts the number of times an element appears in the list
list16 = [1,2,3,4,6,6,6,8,9]
print(list16.count(6))

In [ ]:
# index() -> Returns the lowest index of element in the list. Gives a ValueError,
# if element is not present in the list
print('The index of the element 6:',list16.index(6))

In [ ]:
# insert() -> inserts the element at the given/specified index in the list.

list16 = [1,2,3,4,6,6,6,8,9]
list16.insert(5, 50)
print(list16)

In [ ]:
# pop() -> Removes an element at the specified index from the list. Index is an optional,
#if no index is specified, then removes the last element of the list
ele = list16.pop()
print('Element removed when no index is given', ele)

ele = list16.pop(5)
print('Element removed when from index 5 is given', ele)

In [ ]:
# remove() -> removes or deletes elements from the list, ValueError is generated if
# the element is not the list. If there are multiple times element is there in the list
# then , first encountered will be deleted

ele = list16.remove(1)

print(ele)
print(list16)

In [ ]:
# reverse() -> reverses the elements of the list 
list17 = [1,2,3,4,5,6,7,8,9,10]
list18 = ['Hello','Good','Morning']
list17.reverse()
list18.reverse()
print(list17)
print(list18)
print(list18[0][::-1])

In [ ]:
# sort() -> Sorts the elements in the list
list19 = [2,4,1,0,-1,5,6,-22]
list19.sort()
print(list19)

In [ ]:
# extend() -> Adds the elements in a list to the end of the another list (gives similar as +)
list18 = ['Good','Students','How','are','you']
list19 = [1,2,3,4,5,6,7,8,9,10]
list19.extend(list18)
print(list19)

# Key points to remember

***insert(), remove(), and sort()*** methods only modify the lists and they dont return any value.

When one list is assigned to another list using the assignment operator(=), then a new copy of the list is not made, instead  both points to same memory location of the list. Any modifications made on any of them will refelect to both. Example is shown in below.

In [ ]:
list20 = [1,2,3,4,5,6,7,8]
list21 = list20
print('List20 - ',list20,'    list21 - ',list21)

list21[6] = 100
print('List20 - ',list20,'    list21 - ',list21)

# Looping in LISTS

***for*** & ***in*** constructs are extremely useful when working with lists.

In [ ]:
#list20 = [1,2,3,4,5,6,7,8]
for i in list20:
  print(i, end=' ')

print()
list23 = ['Hello', 'Good', 'Morning','how','are','you']

for i in list23:
  print(i,end=' ')

In [ ]:
# sum and average of numbers in the given list

num_list = [11,21,31,41,51,61,71,81,91,101]
sum = 0

for i in num_list:
  sum+=i

print('Sum of the number in the lists is :',sum)
print('The average of the numbers in the list is :',sum/len(num_list))

In [ ]:
# Enumarate function

for index, i in enumerate(num_list):
  print(i, 'is at index ',index)

In [ ]:
# printing the index of the elements in the list

for i in range(len(num_list)):
  print(i,end=' ')

In [ ]:
#Using iterator: An iterator can be created with built-in iter().
# it used to loop over the elements of the list.
num_list = [10,20,30,40,50,60,70,80,90]
it = iter(num_list)
for i in range(len(num_list)):
  print('Element at index ',i,' is ',next(it))

In [ ]:
lt = []
for i in range(1,11):
  lt.append(i**2)

print(sum(lt))

385
385

# List Comprehensions
Python supports computed lists called list comprehensions.
Syntax:
```
List = [ expression for variable in sequence]
```
Here the expression is evaluated once, for every item in the sequence.

List comprehensions help to create lists in a concise way.

It is useful when each element is obtained by applying some operations to each member of another sequence or iterable.

List comprehension is also used to create a subsequence of those elements that satisfy a certain condition.

In [ ]:
# normal way to create a list of cubes
cubes = []

for i in range(11):
  cubes.append(i**3)
print('Cubes of numbers from 1-10',cubes)

Cubes of numbers from 1-10 [0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [ ]:
# Finding the cubes using List comprehenshions

cubes1 = [i**3 for i in range(11)]
print(cubes1)

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [ ]:
'''Using list comprehenshions to combine two elements
In other words, creating a list of tuples.
'''
numbers = [1,2,3,4,5]
#alphabets = [1,2,3,4,5]
alphabets = ['a','b','c','d','e']
print([(x,y) for x in numbers for y in alphabets])

[(1, 'a'), (1, 'b'), (1, 'c'), (1, 'd'), (1, 'e'), (2, 'a'), (2, 'b'), (2, 'c'), (2, 'd'), (2, 'e'), (3, 'a'), (3, 'b'), (3, 'c'), (3, 'd'), (3, 'e'), (4, 'a'), (4, 'b'), (4, 'c'), (4, 'd'), (4, 'e'), (5, 'a'), (5, 'b'), (5, 'c'), (5, 'd'), (5, 'e')]

In [ ]:
'''Using list comprehenshions to combine two elements
only if they are not same
'''
numbers = [1,2,3,4,5]
alphabets = [1,2,3,4,5]

print([(x,y) for x in numbers for y in alphabets if x!=y])

[(1, 2), (1, 3), (1, 4), (1, 5), (2, 1), (2, 3), (2, 4), (2, 5), (3, 1), (3, 2), (3, 4), (3, 5), (4, 1), (4, 2), (4, 3), (4, 5), (5, 1), (5, 2), (5, 3), (5, 4)]

#FUNCTIONAL PROGRAMMING
Functional programming decomposes a problem into set of functions.
* filter()
* map()
* reduce()

#filter()
It constructs a list from those elements of the list for which a function returns True.
```
filter(function, sequence)
```
filter() function returns a sequence that contains items from the sequence for which the function is True.
It sequence is string , Unicode or a tuple, then the result will be of the same type, otherwise always a list

In [ ]:
# list of number divisible by 2 or 4 using list comperhension
def check(x):
  if (x%2 == 0 or x %4 ==0):
    return 1

evens = list(filter(check, range(2,22)))
print(evens)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [ ]:
# prime numbers
def prime(num):
  factors = 0
  for i in range(1,num):
    if num % i ==0:
      factors+=1
  if factors == 1:
    return 1

primes = list(filter(prime, range(1,20)))
print(primes)

In [ ]:
# finding perfect numbers
def perfect(num):
  sum = 0
  for i in range(1,num):
    if num % i ==0:
      sum = sum+i
  if sum == num:
    return 1

perfect_nums = list(filter(perfect,range(1,100)))
print(perfect_nums)

#map() function
map() function applies a particular function to every element of a list. 
```
map(function, sequence)
```
It returns the modified list.
The map() function calls function(item) for each item in the sequence and returns a list of the return values.

In [ ]:
# doubling the each item of the list.

def mul_2(x):
  return x * 2

num_list = [10,20,30,40,50]
print('original list', num_list)
update_list = list(map(mul_2,num_list))
print('List after doubling each number in the list:')
print(update_list)

original list [10, 20, 30, 40, 50]
List after doubling each number in the list:
[20, 40, 60, 80, 100]

In [ ]:
# finding the cubes with in range
def power(num):
  return num**3


cubes = list(map(power, range(1,10)))
print(cubes)

[1, 8, 27, 64, 125, 216, 343, 512, 729]

More than one sequenc can also be passed in the map() function, and following points to keep in mind:
* The function must have as many arguments as there are sequences.
* Each argument is called with the corresponding item from each sequence (None if one sequence is shorter than another).

In [ ]:
def add(x,y):
  return x+y

list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
list3 = list(map(add,list1,list2))
print(list3)

[7, 9, 11, 13, 15]

# reduce() function
The reduce() function returns a single value generated by called the function on the first two items of the sequence, then on the result and the next time, so on.
```
reduce(function, sequence)
```

#Points to remember to use reduce() function

* If there is only one item in the sequence, then it is returned
* If the sequence is empty an exception is raised.
* Creating a list in a very extensive range will generate a MemoryError or OverflowError.

In [ ]:
# import the functools 
import functools
def add(x,y):
  return x + y


num_list = [1,2,3,4,5]
print('Sum of the values in the list:')
print(functools.reduce(add, num_list))

Sum of the values in the list:
15

In [ ]:
print(functools.reduce(add,primes))

77